// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc.team839.robot.subsystems;

import org.usfirst.frc.team839.robot.commands.DriveWithJoysticks;
import org.usfirst.frc.team839.robot.RobotMap;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *The drivetrain
 */
public class Drivetrain extends Subsystem 
{
    RobotDrive robotDrive = RobotMap.robotDrive;
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() 
    {
        setDefaultCommand(new DriveWithJoysticks());
    }
    
    public int getLeftEncoderPosition()
    {
    	return RobotMap.backLeftMotor.getEncPosition();
    }
    
    public int getRightEncoderPosition()
    {
    	return RobotMap.backRightMotor.getEncPosition();
    }
    
    public void setDriveSpeeds( double dLeft, double dRight )
    {
        robotDrive.tankDrive( dLeft, dRight, true);
    }
    
    public void stop()
    {
        robotDrive.drive( -.1, -.1 );
        robotDrive.drive( 0, 0 );
    }

	public static double inchesToTicks(double distanceInches)
	{
		
		return 1440/(31.42/2.54)*distanceInches;
	} 
}
